[main]
plc_host = "192.168.100.100"
plc_port = "801"
mqtt_host = "172.17.0.1"
plc_timeout = 5000 # in milliseconds
cycle_time = 100 # in miliseconds
max_delay = 100 # in miliseconds

[from_ads]
"MAIN.dInputBool" = { length = "PLCTYPE_BOOL", trans_mode = "ADSTRANS_SERVERONCHA" }
"MAIN.nVarInteger" = { length = "PLCTYPE_INT", trans_mode = "ADSTRANS_SERVERCYCLE", cycle_time = 5000}
